{{ if .Values.serviceMonitor }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "marketbot.fullname" . }}
  namespace: {{ .Values.prometheusOperatorNamespace }}
  labels:
    app.kubernetes.io/name: {{ include "marketbot.name" . }}
    helm.sh/chart: {{ include "marketbot.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  endpoints:
  - interval: 30s
    port: metrics
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "marketbot.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
{{ end }}