name: Release
on:
  push:
    branches:
      - master
    paths:
      - "charts/**"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Configure Git
        run: |
          git config user.name "travisgroth"
          git config user.email "travisgroth@users.noreply.github.com"
      - name: Run chart-releaser
        uses: desimone/chart-releaser-action@master
        env:
          CR_TOKEN: "${{ secrets.CI_TOKEN }}"
        with:
          charts_dir: charts
          charts_repo_url: https://travisgroth.github.io/helm-charts/

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Run chart-testing
        id: lint
        uses: helm/chart-testing-action@v1.0.0-rc.2
        with:
          command: lint
          config: .ct-release.yaml
